# vim: set fenc=utf-8 ts=2 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}}:
version: "3.3"

services:
  terraria:
    container_name: terraria
    restart: on-failure:5
    tty: true
    build: .
    ports:
      - "7777:7777"
    networks:
      net:
    volumes:
      - data:/home/terraria/data
      - /etc/localtime:/etc/localtime:ro

networks:
  net:

volumes:
  data:
