version: "3.8"

services:
  terraria:
    container_name: terraria
    restart: always
    tty: true
    build: .
    ports:
      - "7777:7777"
    networks:
      net:
        ipv4_address: 172.100.1.100
    volumes:
      - data:/home/terraria
      - /etc/localtime:/etc/localtime:ro

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.100.1.0/16"

volumes:
  data:
