#!/bin/sh
# vim: set fenc=utf-8 ts=2 sw=0 sts=0 sr et si tw=0 fdm=marker fmr={{{,}}} pa+=./lua pa+=./lua:

# {{{ Variables
  _game="terraria"
  _user=$_game
  _folder=/home/$_user
# }}}

# {{{ Command-line options
  while [ $1 ]; do
    case $1 in
    'start' )
      screen -S $_game $_folder/startServer.sh
      exit
      ;;

    'console' )
      screen -x $_game
      exit
      ;;

    esac
    shift
  done

  echo No option given. Use \'start\' or \'console\'.
# }}}
